# -*- coding: utf-8 -*-
"""7/01/2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JDxbaXCQPK4h-CuBQoh6Dyf6QW3sDY0
"""

a='hello world'
b=a.lower()
print(b)

a='hello world'
b= a.replace('hello','hi')
print(b)

a='123yy'
b=a.isdigit()
print(b)

r = range(10)
print(r)
my_list = list(r)
print(my_list)

text = "Hello World! PYTHON is Fun."
swapped_text = text.swapcase()
print("Original Text:",text)
print("swapped Case Text:",text)

my_list = list(range(5,16,2))
print(my_list)